[WhisperOutput]
message_matcher = "Type == 'heka.statmetric'"
base_path = "/var/lib/graphite/whisper"
default_agg_method = {{ whisper_agg_method }}
default_archive_info = "{{ retention_policy }}"
folder_perm = "755"
