---
options:
  deb_url:
    type: string
    default: "https://github.com/mozilla-services/heka/releases/download/v0.9.2/heka_0.9.2_amd64.deb"
    description: "Url to a debian package for heka"
  deb_md5:
    type: string
    default: '8d08023d5fb31d0bb46d7943c5e1aca9'
    description: "MD5 for result of 'deb_url'"
  port:
    type: int
    default: 5565
    description: "Primary tcp listening port for hekad"
  whisper_aggegration_method:
    type: int
    default: 1
    description: |
      Default aggregation method to use for each whisper output
      file. Supports the following values:

        (0) Unknown aggregation method.
        (1) Aggregate using averaging. (default)
        (2) Aggregate using summation.
        (3) Aggregate using last received value.
        (4) Aggregate using maximum value.
        (5) Aggregate using minimum value.

  jujud_logs:
    type: boolean
    description: |
      Collect jujud machine zero logs.

  juju_agent:
    type: string
    default: 'none'
    description: |
      Collect juju agent logs.

      Defaults to `none` for no logs collected.

      - `all`: collect all agents unit or machine
      - `machine`: only collect machine log
      - `self`: only collect log for unit agent for heka-hub
      - `unit`: only collect logs from unit agents (including heka-hub)


  enable_ui:
    type: boolean
    description: "Enable dashboard"
  extra_config:
    type: string
    description: "A whitespace delimited list of urls to tarballs or a git repositories with additional toml config or sandbox code to run through templating and add to /etc/heka.d and /usr/share/heka/sandbox"
  rstout:
    type: boolean
    default: false
    description: "Print all messages to stdout formatted w/ RestructuredText for debugging"