#!/bin/bash

set -e
apt-get install -yq python-pip git python-dev
pip install --src=/opt/python-src -r hooks/requirements.txt
HOSTS='/etc/ansible/hosts'
mkdir  -p /etc/ansible
echo "localhost ansible_connection=local" > $HOSTS
ansible-playbook -c local -vvv playbook/main.yml --tags install
